version: "3.8" # Atualize para uma versão compatível com healthchecks

services:

  mongodb:
    image: "mongo:7.0"
    container_name: mongodb
    environment:
      MONGO_INITDB_DATABASE: lowcoder
      MONGO_INITDB_ROOT_USERNAME: lowcoder
      MONGO_INITDB_ROOT_PASSWORD: secret123
    volumes:
      - ./lowcoder-stacks/data/mongodb:/data/db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "127.0.0.1/test", "--eval", "quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 40s

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 10

  lowcoder-api-service:
    image: lowcoder-ce-api-service:latest
    container_name: lowcoder-api-service
    environment:
      LOWCODER_PUBLIC_URL: "http://localhost:3000/"
      LOWCODER_PUID: "9001"
      LOWCODER_PGID: "9001"
      LOWCODER_MONGODB_URL: "mongodb://lowcoder:secret123@mongodb/lowcoder?authSource=admin"
      LOWCODER_REDIS_URL: "redis://redis:6379"
      LOWCODER_NODE_SERVICE_URL: "http://lowcoder-node-service:6060"
      LOWCODER_MAX_QUERY_TIMEOUT: 120
      LOWCODER_MAX_REQUEST_SIZE: 20m
      LOWCODER_EMAIL_AUTH_ENABLED: "true"
      LOWCODER_EMAIL_SIGNUP_ENABLED: "true"
      LOWCODER_CREATE_WORKSPACE_ON_SIGNUP: "true"
      LOWCODER_DB_ENCRYPTION_PASSWORD: "lowcoder.org"
      LOWCODER_DB_ENCRYPTION_SALT: "lowcoder.org"
      LOWCODER_CORS_DOMAINS: "*"
      LOWCODER_API_KEY_SECRET: "5a41b090758b39b226603177ef48d73ae9839dd458ccb7e66f7e7cc028d5a50b"
    restart: unless-stopped
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./lowcoder-stacks:/lowcoder-stacks
      - ./lowcoder-stacks/assets:/lowcoder/assets
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:8080 | grep 'Lowcoder API is up and running'"]
      interval: 3s
      timeout: 5s
      retries: 10

  lowcoder-node-service:
    image: lowcoder-ce-node-service:latest
    container_name: lowcoder-node-service
    environment:
      LOWCODER_PUID: "9001"
      LOWCODER_PGID: "9001"
      LOWCODER_API_SERVICE_URL: "http://lowcoder-api-service:8080"
    restart: unless-stopped
    depends_on:
      lowcoder-api-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:6060 | grep 'Lowcoder Node Service is up and running'"]
      interval: 3s
      timeout: 5s
      retries: 10

  lowcoder-frontend:
    image: lowcoder-ce-frontend:latest
    container_name: lowcoder-frontend
    ports:
      - "3000:3000"
    environment:
      LOWCODER_PUID: "9001"
      LOWCODER_PGID: "9001"
      LOWCODER_API_SERVICE_URL: "http://lowcoder-api-service:8080"
      LOWCODER_NODE_SERVICE_URL: "http://lowcoder-node-service:6060"
    restart: unless-stopped
    depends_on:
      lowcoder-node-service:
        condition: service_healthy
      lowcoder-api-service:
        condition: service_healthy
    volumes:
      - ./lowcoder-stacks/assets:/lowcoder/assets
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:3000 || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 10